### ISSUE TITLE
Program killed unexpectedly 

### ISSUE THREAD

**Issue by Yyyyao712** [ilnehc96/HKU-DASC7606-A1#15]
I'm encountering an issue when running the command “python train.py…” . Each time I attempt to execute this script, the process gets terminated unexpectedly with a "Killed" message. Has anyone encountered a similar issue or have suggestions on how to resolve this?

**Comment by cychiuak** [comment]
Maybe you forget you activate GPU before training? My process is killed before and its solved by activating GPU.

**Comment by Yyyyao712** [comment]
Do you mean that I should run “conda activate retinanet” every time I restart terminal?

**Comment by cychiuak** [comment]
I remember I ran Conda activate retinanet and gpu-interactive, then it works

**Comment by ilnehc96** [comment]
@Yyyyao712 You need gpu-interactive. See GPU Farm instructions.

**Comment by Yyyyao712** [comment]
I did gpu-interactive and conda activate, then cd DASC7606, and run train.py, but still get killed.

**Comment by ilnehc96** [comment]
@Yyyyao712 Could you post the error message, or a screenshot? Killed should not be related to conda.

**Comment by Yyyyao712** [comment]
![715D7912-F364-4A18-941F-C939ADAFDF33](https://github.com/ilnehc96/HKU-DASC7606-A1/assets/161790680/83c701a7-0b58-4904-a7bf-ebef05e3730e)


please have a look, tks.
